### ISSUE TITLE
My results is different from yours, error or not?

### ISSUE THREAD

**Issue by liamxg** [tgvaughan/HK_2018_MiniProject#2]
<img width="209" alt="image" src="https://user-images.githubusercontent.com/46078579/229025749-5490bb9e-a696-40e5-8113-65277d02834d.png">

**Comment by liamxg** [comment]
@tgvaughan

**Comment by tgvaughan** [comment]
Hi @liamxg,  this was a project for a workshop I taught at in 2018.  It was never designed to be used in a standalone fashion.  If you're looking for phylodynamics tutorials, head over to https://taming-the-beast.org.
